#!/usr/bin/env bash
# Generate the frontend architecture doc (overview + folder-only tree).
# Usage: bash script/generate-frontend-architecture.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$ROOT_DIR"

SRC="src"
OUT="docs/architecture-frontend.md"

if [[ ! -d "$SRC" ]]; then
  echo "Not found: $SRC" >&2
  exit 1
fi

print_tree() {
  local dir="$1"
  local prefix="$2"
  local -a children=()
  local entry
  while IFS= read -r entry; do
    children+=("$entry")
  done < <(find "$dir" -mindepth 1 -maxdepth 1 -type d | sort)
  local total=${#children[@]}
  local i
  for ((i = 0; i < total; i++)); do
    local child="${children[i]}"
    local name="${child##*/}"
    if ((i == total - 1)); then
      echo "${prefix}└── ${name}"
      print_tree "$child" "${prefix}    "
    else
      echo "${prefix}├── ${name}"
      print_tree "$child" "${prefix}│   "
    fi
  done
}

TREE="$(printf '%s\n' "$SRC"; print_tree "$SRC" "")"

mkdir -p "$(dirname "$OUT")"

{
  printf '%s\n' "# Frontend Architecture (FSD v2.1)"
  printf '%s\n' ""
  printf '%s\n' "> Auto-generated by \`script/generate-frontend-architecture.sh\`. Do not edit manually."
  printf '%s\n' ""
  printf '%s\n' "## Overview"
  printf '%s\n' ""
  printf '%s\n' "Stack: Tauri 2 + Vanilla TypeScript + Vite."
  printf '%s\n' ""
  printf '%s\n' "| Layer      | Role |"
  printf '%s\n' "| ---------- | ---- |"
  printf '%s\n' "| \`app\`      | Global initialization: providers, router, styles, entry point. No business logic or page/feature UI. |"
  printf '%s\n' "| \`pages\`    | Route-level composition, owns page logic (UI, forms, validation, fetching, state). Keep code in the page until extraction is justified. |"
  printf '%s\n' "| \`features\` | Independent, reusable user interactions with a narrow responsibility and a single shared implementation. Extract only when used in multiple places. |"
  printf '%s\n' "| \`entities\` | Reusable domain models (types, logic, state). Starting without this layer is valid. |"
  printf '%s\n' "| \`shared\`   | Infrastructure with no business logic, organized by segment (\`ui\`, \`lib\`, \`api\`, ...). May contain app-aware code (route constants, endpoints, DTOs). |"
  printf '%s\n' ""
  printf '%s\n' "## Directory tree"
  printf '%s\n' ""
  printf '%s\n' '```text'
  printf '%s\n' "$TREE"
  printf '%s\n' '```'
  printf '%s\n' ""
  printf '%s\n' "Regenerate:"
  printf '%s\n' ""
  printf '%s\n' '```bash'
  printf '%s\n' "bash script/generate-frontend-architecture.sh"
  printf '%s\n' '```'
} > "$OUT"

echo "Generated: $OUT"
